'use client';

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#fff',
    padding: 30,
    fontFamily: 'Helvetica',
    fontSize: 12,
    lineHeight: 1.6,
  },
  header: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#111827',
  },
  section: {
    marginBottom: 16,
  },
  bold: {
    fontWeight: 'bold',
    color: '#1f2937',
  },
});

export function ReportPDF({ clientName, reportText }: { clientName: string; reportText: string }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Client Report – {clientName}</Text>
        <View style={styles.section}>
          <Text>{reportText}</Text>
        </View>
        <Text style={styles.bold}>Generated by KeepFlow AI</Text>
      </Page>
    </Document>
  );
}